runtime:
  cache_dir: ./.cache/antora

site:
  title: Knative on OpenShift
  url: https://openshift-knative.github.io/docs
  start_page: docs::index.adoc  
content:
  sources:
    - url: https://github.com/openshift-knative/docs.git
      branches: master      
ui:
  bundle:
    url:  https://github.com/finp/arotna.org/raw/master/ui-bundle.zip
 