runtime:
  cache_dir: ./.cache/antora

site:
  title: Knative on OpenShift
  url: https://openshift-knative.github.io/docs
  start_page: docs::pages/index.adoc
  
content:
  sources:
    - url: https://github.com/openshift-knative/docs.git
      branches: master
      start_path: documentation     
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./gh-pages
